### ISSUE TITLE
カレンダー機能の実装について

### ISSUE THREAD

**Issue by pompompurin456** [TechBowl-japan/TechTrain-Issue-Report#1]
**現在直面してみる問題はなんでしょ？**
現在はメンターを指定して面談時間を設定しているが時間がなかなか取れなくなり、メンター指定より時間指定をしたいと考えている

**どういう機能あれば解決しそうでしょうか・・・？**
カレンダーに時間が空いているメンターの一覧のようなものを作成していただきたい。
→見ただけで誰が空いているのかを確認することができる

**補足**
テキストで不十分だと感じた場合はZoomなどで話できます！！！

**Comment by SuguruOoki** [comment]
もう少し話が聞きたい！

**Comment by SuguruOoki** [comment]
# 概要

1. 自分が時間があったからメンターに時間を合わせにいけた
2. 今自分の時間がなくなってきたので、一覧としてみれると、合わせにいきやすい

**Comment by SuguruOoki** [comment]
# Issue

解決したいのは、空いた時間メインで予約を入れたい
メンターさんみんな強いから誰に聞いてもぶっちゃけ自分よりもできるはず。誰でもいいから聞きたい。

ex)

1. 19:00に予約したい
2. いつものメンターさんが19:00空いてない
3. 同じ時間に空いているメンターさんがおすすめに出てきてくれたら解決

↑スキル別予約への遷移にしてみると良いかも。

**Comment by pompompurin456** [comment]
カレンダー機能について

**背景：**
1. 相談する内容が言語化できるようになったため面談相手との相談内容のすり合わせができるようになった

1. 日中は業務などで時間を使っているため時間を作るのが難しくなっている

1. 学生から社会人になるにあたりメンターさん指定より、時間指定の方が旨味を感じる

**提案：**

1. スキル別とメンター指定の違いを理解している人が少ないため理解度を高める
→スキル別という文言がわかりにくかも時間指定のようにする方がわかりやすいと感じている

1. 現在のUIデザインだとカレンダーで空いてる日付は直感的に理解することができるが時間まで見ることに時間がかかる
→日付tap、時間一覧の表示（この作業をメンターさんを変えるたびに行う必要がある）

**Comment by SuguruOoki** [comment]
スキル別のところで、もう少しマッチングの精度を上げてから、導入させてもらうことにします！
今しばらくお待ちください！

**Comment by SuguruOoki** [comment]
現在対応を進めています。

**Comment by SuguruOoki** [comment]
ほとんど実装を終えているため、来週にはリリース予定。

**Comment by SuguruOoki** [comment]
時間ベースの予約機能をリリースしました！
触ってみてもらえると嬉しいです！
指摘に大感謝！🙇‍♂️
