### ISSUE TITLE
分野・言語を絞った場合にメンターの空いている時間を一覧で見たい

### ISSUE THREAD

**Issue by bassa01** [TechBowl-japan/TechTrain-Issue-Report#10]
**現在直面してみる問題はなんでしょ？**
分野・言語を絞った場合にスキル別と違ってメンターの空き時間をまとめてみる機能がない

**どういう機能あれば解決しそうでしょうか・・・？**
分野・言語を絞ったのちにまとめて時間を表示する機能をつける

**補足**
あれば嬉しいけどなくても困らないのでFutureで

**Comment by SuguruOoki** [comment]
要望ありがとうございます！
時間を一気に見るために現在状況だと負荷が高くなってしまうという状況がありますので、検討させてください！（個人的にも欲しいのでいつか実現したいと考えてますっ！）
