### ISSUE TITLE
プロフィール編集の「就職活動状況を教えてください ★」のリストが非常に読みにくい

### ISSUE THREAD

**Issue by bassa01** [TechBowl-japan/TechTrain-Issue-Report#11]
**現在直面してみる問題はなんでしょ？**
プロフィール編集の「就職活動状況を教えてください ★」のリストの背景が白で文字が白なので絶望的に読みにくい

**どういう機能あれば解決しそうでしょうか・・・？**
背景を黒にしてほしい
もしくは文字を黒にしてほしい

**補足**
最初に入力するときも白背景に白文字で絶望的に読みにくかったので、できたら白背景に黒文字のほうが個人的には読みやすいかなと思っています。
黒は暗いイメージを持つ方が多いので、最初から黒背景だとヤバい組織みたいに見えるかもしれないです(無料を謳っている以上、入ってこようとする人もそれなりに警戒すると思います)

**Comment by bassa01** [comment]
追記 : 「メイン利用目的: Academyコース(スキルアップしたい方) or Careerコース(就職/転職したい方) ★」 のところも同じです

**Comment by SuguruOoki** [comment]
@soft-bear 
こちらどのOS、機種で白背景になっているのかをいただけますか？

**Comment by bassa01** [comment]
Windows NT 10.0; Win64; x64
機種としてはFujitsuのlifebookです(これ要りますか？)
Chrome/81.0.4044.138

**Comment by bassa01** [comment]
![image](https://user-images.githubusercontent.com/41140188/82777159-46df4680-9e88-11ea-94f9-370fd7fb7b89.png)

**Comment by SuguruOoki** [comment]
![スクリーンショット 2020-05-29 12 12 27](https://user-images.githubusercontent.com/16362021/83217071-b06f9580-a1a5-11ea-95e9-bc5de04cf16e.png)

バージョンが少し異なりますが、現状MacのChromeの場合、上記のような表示となっています。
WindowsのChrome特有の現象のような気がしますので、調査しますね！

**Comment by TakumaKurosawa** [comment]
こちらで一旦ユーザアンケート実施中
https://techbowl.slack.com/archives/C9J4LQ98D/p1595729622119700

**Comment by bassa01** [comment]
これなのですが、火狐でも同様になりました。
![image](https://user-images.githubusercontent.com/41140188/88473240-97d9ec80-cf56-11ea-82c9-0e95bf25e8fe.png)

**Comment by TakumaKurosawa** [comment]
@soft-bear さん
ありがとうございます！
一瞬火狐ってなんだ！？ってなりましたwww

**Comment by TakumaKurosawa** [comment]
Slackにて調査をしたところ、 @伊藝 巧也 さんが自身の環境でデバッグして解決案を提示してくださいました🎉

>余計なお世話かもしれませんけど、selectタグにbackground-color: #25272E;を追加してみたらいい感じに見やすくなりました！
カラーコードは背景と同じ色を使わせていただきました！


![image (1)](https://user-images.githubusercontent.com/39955827/88473368-c4423880-cf57-11ea-8284-42270a506bae.png)

**Comment by TakumaKurosawa** [comment]
僕の環境で特に影響がでなさそうであればこちらの対応で実装しようと思います。
