### ISSUE TITLE
メンターのお気に入り機能

### ISSUE THREAD

**Issue by bassa01** [TechBowl-japan/TechTrain-Issue-Report#12]
**現在直面してみる問題はなんでしょ？**
どのメンターがどのくらいおすすめなのかわからない

**どういう機能あれば解決しそうでしょうか・・・？**
メンターに対するお気に入り機能を作って、お気に入りの個数から「人気のメンター~=わかりやすいメンター」を選びやすくできればいいなと思いました。(ただ、これはこれで一部のメンターに負荷がかかる可能性がありますね……)

**Comment by SuguruOoki** [comment]
ちょっと評判などのセンシティブな問題も出てくるので検討させてください！

**Comment by SuguruOoki** [comment]
現状はまだやらないことに決めさせていただきました！
理由としては次のとおりです！

1. 懸念の通り、すでにメンターの偏りが出ていること
2. TechTrainとしてはいろんなメンターからフィードバックをもらった方が、エンジニアとしての成長が得られると考えていること
3. お気に入りされたからそのメンターがコーチングがうまいかというとそうではない可能性もある。人は、一番最初に続け始めたことをコストがかかったとしてもずっと続ける心理傾向にあるため

要望いただいた機能としては、よくある機能なので事業の段階によっては導入が必要となってくると思います！
現在はやらないという判断をさせていただいただけなので、今後この意見を参考にタイミングを見て導入する可能性もあります！
よろしくお願いします！
