### ISSUE TITLE
面談登録時のエラー

### ISSUE THREAD

**Issue by dionomusuko** [TechBowl-japan/TechTrain-Issue-Report#2]
**不具合内容の説明**
面談登録画面で日時の選択をした際に、「その時間は埋まってます」みたいなエラーメッセージ が出ることがあった。他の時間を選んでも何度か同じエラーが続いた。

**再現させるための手順**
1. https://techbowl.co.jp/techtrain/reserve/group
2. メンターを選ぶ
3. 日時をクリックする
4. 「その時間は埋まってます」のようなエラーメッセージが表示される

**期待していた動作**
時間を選ぶと予約完了（埋まっている日付は、出ない仕様だと思っています）

**Comment by SuguruOoki** [comment]
こちら現在対応させていただいております！
原因としましては、メンターの予定更新の頻度が1日に一回となっているためです！
頻度を上げることでいったん対応させていただく予定です！

**Comment by SuguruOoki** [comment]
こちら頻度を上げることで、対応しました！
また問題があれば教えてください！🙇‍♂️
