### ISSUE TITLE
メンターの絞り込み＆曖昧検索機能

### ISSUE THREAD

**Issue by TakumaKurosawa** [TechBowl-japan/TechTrain-Issue-Report#3]
**現在直面してみる問題はなんでしょ？**
今直面している問題があれば、教えてください！
解決してTechTrainをより良いサービス、コミュニティにしていきたいと考えています！

- ユーザにネクストアクションを提示する時に、どのメンターなら合いそうかが分からない。
- 以前Windowsユーザの方が環境構築で困っていたが、Windowsユーザのメンターさんを探せる仕組みがなく、紹介できなかった。

**どういう機能あれば解決しそうでしょうか・・・？**
できるだけ、明確に機能の説明を書いてもらえると助かります！
自分の中でも言語化しにくいと考えているのであれば、それも含めて教えてください！

- 使っているOSや解決したい課題を曖昧検索することで最適なメンターをリコメンドしてくれる機能が欲しい
- 過去のアンケート結果を元に、どんな質問を答えてきたメンターなのかも含めて検索条件にできそう

**補足**

ユーザ、メンターどちらも経験させていただいたことでさらにTechTrainが大好きになりました！今後ともTechTrainの成長を間近で見られるように精進してまいります！

**Comment by SuguruOoki** [comment]
> どんな質問を答えてきたメンターなのかも含めて検索条件にできそう

こちら現在検討の上、実装させてもらいます！
どんな質問に答えてきたメンターなのかについては、取れているため、それをうまい形で出せればなと考えてますw

**Comment by SuguruOoki** [comment]
こちらリコメンドの精度を上げていく施策を練り上げてます！しばらくお待ちを！

**Comment by TakumaKurosawa** [comment]
ご検討いただきまして、ありがとうございます！
今後のアップデート楽しみにしています。

**Comment by SuguruOoki** [comment]
# 検討事項

## そもそもの課題は何か？

1. 質問内容に対してあっているメンターがわからない
2. メンターを先に選んでから質問内容を書いているので、フロー的に無理がある

### 情報の関係性

1. 質問とメンターを紐付ける
2. ユーザーとメンターを紐づける

コミュニティとしてTechTrainをやっていくのであれば、思想的には2が望ましいと考えている。
が、使い勝手としては、質問を入力してからおすすめのメンターが観れると嬉しいかも。

### 解決のための施策

1. 質問テンプレートをそもそもアップデートする
2. 質問に技術タグを入力した時点で技術マッチングをしてみる

こちらを解決のための施策として考えています。

**Comment by SuguruOoki** [comment]
ひとまず検索については少し改善を裏で加えました！
また、これから質問の際のテンプレートを用意することで事前にメンター側が質問の内容をもう少しわかるようにすることで対応をしようと思います！

**Comment by SuguruOoki** [comment]
検索について少し改善を加えたため、いったんこのIssueをクローズにさせてもらいます！
全文検索については追々対応を進めていきます！楽しみに待っててもらえると嬉しいです！
本当にいつもご協力大感謝！！！
