### ISSUE TITLE
「メンター」タブの遷移先を「メンターを指名するページ」(https://techbowl.co.jp/techtrain/reserve/personal)にして欲しい

### ISSUE THREAD

**Issue by TakumaKurosawa** [TechBowl-japan/TechTrain-Issue-Report#4]
**現在直面してみる問題はなんでしょ？**
今直面している問題があれば、教えてください！
解決してTechTrainをより良いサービス、コミュニティにしていきたいと考えています！

- 初めて利用する人や、あまり詳しくTechTrainのサイトを見ないユーザは恐らくグローバルナビゲーションから飛べるページが全てだと感じてしまいます。
- 私の個人的な意見として、[メンター一覧ページ](https://techbowl.co.jp/techtrain/mentor)はメンターのカテゴリ分けもされておらずメンターを探すという目的においては使いにくいページだと考えます。

**どういう機能あれば解決しそうでしょうか・・・？**
できるだけ、明確に機能の説明を書いてもらえると助かります！
自分の中でも言語化しにくいと考えているのであれば、それも含めて教えてください！

- グローバルナビゲーションの「メンター」を押したら、[メンターを指名する](https://techbowl.co.jp/techtrain/reserve/personal)ページに遷移してくれた方が嬉しいです。

**補足**

**Comment by SuguruOoki** [comment]
ありがとうございます！導入を検討させてもらいます！
現状このまま導入すると、「メンターを指名する」のページには、技術の検索が導入されていない関係で、使いやすいとは言いづらいものとなってしまいます。
検索と合わせて導入させてもらおうと考えています！
よろしくお願いします！

**Comment by SuguruOoki** [comment]
こちら対応させてもらいました！
意見がありがとうございました！

**Comment by TakumaKurosawa** [comment]
TechTrainサービスページでも確認させていただきました！
採用していただきましてありがとうございます！
面談予約の推移など、効果検証の結果も楽しみにしています！
