### ISSUE TITLE
具体的なアウトプットが見えるといい

### ISSUE THREAD

**Issue by ryutofukuzawa** [TechBowl-japan/TechTrain-Issue-Report#5]
メンターが具体的に関わったサービス名の記載があると、より何が得意か、自分の持つ課題を解決してもらえるか、のイメージが湧く気がします。
(Githubのコードを覗けるほどレベルの高い層ばかりではない気もしているので)

**Comment by SuguruOoki** [comment]
ありがとうございます！
こちらはメンターの所属先との交渉や調整などが必要となり
時間がかかることとなるためいったんクローズとさせてください！
