### ISSUE TITLE
Techtrain「面談予約」ページ→「相談したい内容を具体的にご記載ください。★」のheightをもう少し大きくしてほしい。

### ISSUE THREAD

**Issue by y-kotti** [TechBowl-japan/TechTrain-Issue-Report#6]
**現在直面してみる問題はなんでしょ？**
「面談予約」ページ→「相談したい内容を具体的にご記載ください。★」の入力ボックスをPCで見ると、weight：488、height：84だが、heightの値が小さすぎる気がする。
相談したい内容を具体的に書こうとすると、どうしても4行こえてしまうので、
どんな文章を書いたか振り返ろうと思ったときに、スクロールしないといけなくなる。

**どういう機能あれば解決しそうでしょうか・・・？**
「相談したい内容を具体的にご記載ください。★」の入力ボックスの
heightを200にしたらちょうどよくなると思いました。

**Comment by SuguruOoki** [comment]
確認の上、実装の方に回させてください！

**Comment by SuguruOoki** [comment]
@y-kotti 
こちら高くしていきますね！
