### ISSUE TITLE
Techtrain「面談予約」ページで、プレビューが見れるといい。

### ISSUE THREAD

**Issue by y-kotti** [TechBowl-japan/TechTrain-Issue-Report#7]
**要望**
「面談予約」ページで自分が何を書いたか最後に確認してから、面談予約を確定させるようにしたい。

**どういう機能あれば解決しそうでしょうか・・・？**
・プレビュー機能

**Comment by SuguruOoki** [comment]
ありがとうございます！
もう少し詳細を面談時に聞かせてください！

**Comment by SuguruOoki** [comment]
@y-kotti 
**書いた理由**

1. 面談予約ページで、見れなくなっちゃってる
2. 後から面談予約内容が見れれば、別になくても良い。

**Comment by SuguruOoki** [comment]
面談の詳細ページで、自分で質問した内容が見れるようになりました！
こちらのIssueをクローズさせていただきます！
