### ISSUE TITLE
Techtrain マイページの「お問い合わせ」を押下しても何も表示されない。

### ISSUE THREAD

**Issue by y-kotti** [TechBowl-japan/TechTrain-Issue-Report#8]
**不具合内容の説明**
私だけだったらすいません。
Techtrain マイページのヘッダーにある、「お問い合わせ」を押下したのですが、
「無題」という名前の真っ白なページが表示されるだけで、利用できません。

**再現させるための手順**

1. https://techbowl.co.jp/techtrain/ にアクセス
2. 「マイページへ」を押下し、マイページに遷移。
3. ヘッダーの「お問い合わせ」を押下。
4. 別タブで「無題」という名前の真っ白なページが表示される。

**期待していた動作**
Slackのアプリケーションが起動される…はず。

**デスクトップ (必要な情報を埋めていただけると助かります🙇‍♂️):**
 - OS: [e.g. Windows10]
 - Browser [e.g. chrome]
 - Version [e.g. Windows10 1909]

**Comment by SuguruOoki** [comment]
ありがとうございます！確認します！

**Comment by SuguruOoki** [comment]
調査中

**Comment by SuguruOoki** [comment]
こちら対応が終わりましたのでクローズします！
してきありがとうございます！
