### ISSUE TITLE
TechTrain「マイページ」の「面談予約を確認」から、面談予約時に入力した「詳細」の内容を確認できない。

### ISSUE THREAD

**Issue by y-kotti** [TechBowl-japan/TechTrain-Issue-Report#9]
**現在直面してみる問題はなんでしょ？**
TechTrain「マイページ」の「面談予約を確認」から、
面談予約時に入力した「詳細の入力」以下の内容を確認できない。

**どういう機能あれば解決しそうでしょうか・・・？**
TechTrain「マイページ」の「面談予約を確認」から、
面談予約時に入力した「詳細の入力」以下の内容を確認できるようにする。

**Comment by SuguruOoki** [comment]
面談の詳細情報を確認できるようにしたため、こちらをクローズさせていただきます！
